SELECT B.USER_ID, B.NICKNAME, SUM(C.PRICE) AS TOTAL_SALES 
FROM USED_GOODS_BOARD C JOIN USED_GOODS_USER B ON C.WRITER_ID = B.USER_ID
WHERE C.STATUS = 'DONE'
GROUP BY B.USER_ID
HAVING TOTAL_SALES >= 700000
ORDER BY TOTAL_SALES